name: units
parameters: |
  __spring.xml=zkagent.xml,http/httpclient.xml,users.xml
  zk.address = 192.168.8.8:2181
  zk.root.path = /
children:
  - name: adduser
    parameters: |
      account = test
      password = test
      fullname = TEST
      email = test@test.com
  - name: jolokia
  - name: jmxsrv
    parameters: |
      jmxmp.port = 9879
      jmxhtml.port = 7083
  - name: jettywebapp
    parameters: |
      webapp.host = 127.0.0.1
      webapp.port = 7080
      webapp.path = /xbeacon
      webapp.category = demo
      webapp.priority = 100