name: units
parameters: |
  __spring.xml=zkclient.xml
  zk.address = 192.168.8.8:2181
children:
  - name: jmxsrv
    parameters: |
      jmxmp.port = 9879
      jmxhtml.port = 7083
  - name: jettywebapp
    parameters: |
      root.path=/test
      webapp.host = 127.0.0.1
      webapp.path = /zkwebui
      webapp.category = demo
      webapp.priority = 100